services:
  rms-frontend:
    container_name: rms-frontend
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:5001 
    networks:
      - rms-shared-network

networks:
  rms-shared-network:
    external: true