services:
  rms-frontend:
    container_name: rms-frontend
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3001:3001"
    env_file:
      - .env  # Docker sẽ nạp file .env tại đây
    environment:
      - NODE_ENV=production
      # Cú pháp ${VAR} sẽ lấy giá trị từ file .env
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL} 
    networks:
      - rms-shared-network

networks:
  rms-shared-network:
    external: true