import { Inter } from "next/font/google";
import "./globals.css";
import BackToTop from "./dashboard/components/BackToTop";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata = {
  title: "ThanHoa Restaurent",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.variable} font-sans antialiased bg-gray-100`}>
        {children}
        <BackToTop />
      </body>
    </html>
  );
}
